# Generated by Django 2.2.7 on 2020-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=300, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='userPass',
            field=models.CharField(default='', max_length=100, verbose_name='pass'),
            preserve_default=False,
        ),
    ]
