# Generated by Django 3.0.6 on 2020-05-07 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0002_auto_20200507_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('price', models.DateField()),
                ('broughtDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='land name')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Contract')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('criticality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='spout name')),
                ('isOn', models.BooleanField(default=False)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Land')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='userPass',
        ),
        migrations.AddField(
            model_name='customer',
            name='isActivated',
            field=models.BooleanField(default=True, verbose_name='is activated'),
        ),
        migrations.AddField(
            model_name='customer',
            name='isBlocked',
            field=models.BooleanField(default=False, verbose_name='is blocked'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default='', max_length=12, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpoutSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOn', models.BooleanField(default=False)),
                ('spout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Spout')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='sensor name')),
                ('type', models.CharField(max_length=100, verbose_name='sensor type')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Land')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='lands',
            field=models.ManyToManyField(to='Customer.Land'),
        ),
    ]
